defaults: &defaults
  ftp_timeout: 3600
  smb_timeout: 3600
  http_timeout: 3600
  folder_timeout: 3600
  max_emails: 10000

  # Настройки прайса emex
  emex_income_rate: 1
  emex_retail_rate: 1.55
  emex_discount_rate_for_price: 0.84
  emex_minimal_retail_rate_for_price: 1.07

  emex_login: 14616
  emex_password: 2b0ffb38
  # Время кеширования результата запроса с емекса по детали
  emex_cache: 10
  emex_timeout: 200

  lc_ws_address: http://192.168.1.42/trade_dda/ws
  lc_ws_login: webservice_test
  lc_ws_password: webservice_test

  catalog_number_len: 20
  manufacturer_len: 20
  max_replaces: 80
  max_discount: 1.29

development:
  <<: *defaults

production:
  <<: *defaults
